openapi: 3.0.3
info:
  title: User subscription API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://user-subscription/api'
paths:
  /users:
    get:
      operationId: findAllUsers
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - fullName
      properties:
        id:
          type: string
          format: uuid
          example: ef88e14a-3422-48b3-aad7-095617d90c8d
        fullName:
          type: string
          example: Соколов Даниил Егорович